
protocol ReceiptRepresentable:
    OriginalPurchaseDateRepresentable {
    
    associatedtype InApp: InAppRepresentable
    
    /**
     Generated by App Store Connect and used by the App Store to uniquely identify the app purchased.
     
     Apps are assigned this identifier only in production. Treat this value as a 64-bit long integer.
     */
    var adamID: Int? { get }
    
    /**
     Generated by App Store Connect and used by the App Store to uniquely identify the app purchased.
     
     Apps are assigned this identifier only in production. Treat this value as a 64-bit long integer.
     */
    var appItemID: Int? { get }
    
    /**
     The app’s version number.
     
     The app's version number corresponds to the value of `CFBundleVersion` (in iOS) or `CFBundleShortVersionString` (in macOS) in the `Info.plist`. In production, this value is the current version of the app on the device based on the `receiptCreationDate`. In the sandbox, the value is always `"1.0"`.
     */
    var applicationVersion: String? { get }
    
    /**
     The bundle identifier for the app to which the receipt belongs.
     
     You provide this string on App Store Connect. This corresponds to the value of `CFBundleIdentifier` in the `Info.plist` file of the app.
     */
    var bundleID: String? { get }
    
    /// A unique identifier for the app download transaction.
    var downloadID: Int? { get }
    
    /**
     The time the receipt expires for apps purchased through the Volume Purchase Program.
     
     If this key is not present for apps purchased through the Volume Purchase Program, the receipt does not expire.
     */
    var expirationDate: Date? { get }
    
    /// An array that contains the in-app purchase receipt fields for all in-app purchase transactions.
    var inApp: [InApp]? { get }
    
    /**
     The version of the app that the user originally purchased.
     
     This value does not change, and corresponds to the value of `CFBundleVersion` (in iOS) or `CFBundleShortVersionString` (in macOS) in the `Info.plist` file of the original purchase. In the sandbox environment, the value is always `"1.0"`.
     */
    var originalApplicationVersion: String? { get }
    
    /// The time the user ordered the app available for pre-order.
    ///
    /// This field is only present if the user pre-orders the app.
    var preorderDate: Date? { get }
    
    /// The time the App Store generated the receipt.
    ///
    /// This value does not change.
    var receiptCreationDate: Date? { get }
    
    /// The type of receipt generated.
    ///
    /// The value corresponds to the environment in which the app or VPP purchase was made.
    var receiptType: ReceiptType? { get }
    
    ///The time the request to the verifyReceipt endpoint was processed and the response was generated.
    var requestDate: Date? { get }
    
    ///An arbitrary number that identifies a revision of your app.
    ///
    ///In the sandbox, this key's value is “0”.
    var versionExternalIdentifier: Int? { get }
}

public enum ReceiptType: String, Codable, CustomStringConvertible {
    case production = "Production"
    case productionVPP = "ProductionVPP"
    case productionSandbox = "ProductionSandbox"
    case productionVPPSandbox = "ProductionVPPSandbox"
    
    public var description: String { rawValue }
}
